const stories = [
    {
        title: 'Chuyện lớp trưởng',
        note: 'Một ngày chủ nhật cuối hè, 21/8/2016',
        story: 'Nhiều lúc nghĩ lại chuyện làm cán bộ lớp, của mình và của các bạn cán bộ lớp mình quen, thấy đúng là một thời trẻ dại.\n' +
            '\n' +
            'Hồi lớp 1, được cô giao cho làm lớp trưởng. Từ đó đến hết lớp 5, năm nào cũng làm lớp trưởng. Hồi đó tưởng làm lớp trưởng là oai lắm, được giáo viên ưu ái bảo kê, không phải sợ ai mà lớp đứa nào cũng phải sợ mình. Lần đầu tiên được hưởng cảm giác có tí chức quyền là thế nào. Mà hồi đó chỉ thấy oai thôi, oai kiểu con nít, chữ vẫn là thằng đếm sĩ số đọc 5 điều bác hồ dạy của thầy cô.\n' +
            '\n' +
            'Lên lớp 3, lớn lên một tí, đã quen làm lớp trưởng, thì bắt đầu biết tận dụng lợi thế hơn, mà nói thẳng ra làm lạm dụng chức vụ quyền hạn. Đỉnh điểm là cái hôm mình đầu têu lôi hội của lớp đi đánh nhau. Đánh nhau thắng  trận hả hê chán rồi thì lúc về bị giáo viên tóm gọn. Lần đầu tiên biết thế nào là trách nhiệm thật của thằng lớp trưởng. Cô phạt mình nặng nhất cả bọn, rồi còn bắt viết bản kiểm điểm có phụ huynh kí. Mang bảng kiểm điểm về cho mẹ, mẹ đánh cho một trận thừa sống thiếu chết vì tội đánh nhau, đến giờ vẫn còn nhớ không quên được. Từ đó cạch, không bao giờ đánh nhau nữa, và cũng từ đó biết thế nào là làm đại ca là phải chịu hết tội lỗi của bọn đàn em. Mặc dù công nhận là hồi đó tội mình cũng nhiều thật.\n' +
            '\n' +
            'Lên lớp 5, lại khôn ra một tí nữa, và đã bắt đầu nhận ra là hóa ra là lớp trưởng không chỉ là thằng sai vặt cúa giáo viên, mà còn là cái bia đỡ đạn của bọn học sinh trong lớp. Có việc gì là giáo viên cũng đưa cho lớp trưởng làm. Lớp trưởng làm thế nào là tùy, hỏng là lớp trưởng chịu chứ không phải mấy thằng quỷ sứ trong lớp. Có tội gì của bọn quỷ sứ trong lớp thì cũng là lớp trưởng gánh hộ một phần, vì ai bảo là lớp trưởng mà không quản được bọn kia. Thế là biết, hóa ra lớp trưởng như cái vùng trũng của lớp, từ giáo viên đến học sinh có cái gì cứ tương hết vào đấy. Từ sau đó cạch, thề không bao giờ làm lớp trưởng nữa.\n' +
            '\n' +
            'Lên lớp 6, cái ngày bầu cán bộ lớp, cô chủ nhiệm hỏi đã ai từng làm cán bộ lớp thì giơ tay. Rút kinh nghiệm,yên lặng, ngồi im thin thít một chỗ. Tiếc là tuy sống sót nhưng vẫn ăn đạn lạc. Cô chủ nhiệm vẫn giao cho mình cái chức lớp phó lao động. Hồi đó chỉ nghĩ làm 1 năm thôi xong chuồn, mà thế nào mà ôm cái chức đó suốt 7 năm trời, từ lớp 6 đến lớp 12. 7 năm ròng rã làm lớp phó lao động, không sót một năm nào. Mà đến bây giờ mình vẫn không thể hiểu nổi cái chức đó sinh ra để làm gì, ngoài việc để cho đẹp đội hình lúc chụp ảnh cán bộ lớp.\n' +
            '\n' +
            'Học lên lớp 8, 4 lớp 7 được sắp xếp lại, giỏi chơi với giỏi, dốt chơi với dốt. Mình lọt top lớp dốt Lại đổi giáo viên chủ nhiệm, lại bầu cán bộ lớp. Cô lại hỏi lai làm cái bộ lớp, mình lại rút kinh nghiệm không giơ tay, mà ai ngờ đâu bị đồng đội phản bội, chỉ luôn mình bảo cô ơi có thằng này làm lớp phó lao động. Thế là lại lớp phó lao động. Chẳng nhớ phải làm gì hồi đấy, chỉ nhớ nhậm chức được mấy ngày thì tự nhiên sau giờ ra chơi phát hiện ra có một con chó đã làm trò vô duyên trong lớp. Điều tra một hồi thì  phát hiện ra là chó của bảo vệ, chẳng biết là nuôi để bảo vệ trường hay là để thi thoảng cải thiện bữa ăn. Chỉ biết là sau khi phát hiện ra vụ đó, cả lớp đã quyết định tụ họp lại bàn xem thằng nào đi dọn. Cãi nhau đùn đẩy một hồi không giải quyết được vấn đề, cả lớp nhớ ra là có mình vừa được bầu làm lớp phó lao động. Lao động là vinh quang, thế nên cả lớp ( trừ mình) quyết định là thằng lớp phó lao động (là mình) nên lao động để chứng minh trình độ làm lớp phó lao động của mình, tức là đi dọn chỗ đó. Điểm sáng chói duy nhất trong chuỗi 7 năm làm lớp phó lao động buồn tẻ của mình.\n' +
            '\n' +
            'Lên lớp 9, cô quyết định bầu lại đổi trưởng của lớp. Mình trước ngày đó thăm dò, đã ngửi được mùi bọn phản bội trong lớp nhất định sẽ bầu mình. Lần này rút kinh nghiệm tẩu vi thượng sách, xin nghỉ ốm đúng hôm bầu đội trưởng, nằm nhà xem TV hả hê lần này thoát kiếp nạn. Đang ngồi xem phim thì tự nhiên thằng bạn thân cùng bàn gọi về, chúc mừng là đã được lên chức. Nghe xong mặt cắt không còn giọt máu, mà lúc đó biết thừa thằng bạn chúc đểu. Sau mấy giây lấy lại bình tĩnh, nghĩ mình không ở đó bọn nó bầu kiểu gì được, hỏi lại là mình có ở đó đâu mà bầu. Thằng phản bội cùng bàn bình tĩnh trả lời lại là trong những người được bầu thì có mỗi mình là không có phản đối gì cả, vì mình không có ở đó mà phản đối, nên là bầu len là đúng rồi. Đúng là vỏ quýt dày có móng tay nhọn, mình đã tưởng mình cao tay rồi mà bọn nó còn cao tay hơn. Được cái là nhờ có cái chức đó mà mình cũng trốn được kha khá buổi học do lấy lý do công vụ. Thôi thì trong cái rủi cũng gọi là có cái may.\n' +
            '\n' +
            'Lên cấp 3, bầu lớp trưởng, cô cho tự ứng cử, mình chẳng buồn giơ tay. Nhưng đến lúc chọn những chức vụ còn lại, lại bọn phản bội lớp 9 làm chỉ điểm cho cô, lại làm lớp phó lao động. Cả 2 năm lớp 10, 11 chẳng làm được cái gì ra hồn, cái chức bé tí tẹo chẳng ai quan tâm. Đến lớp 12, cô ra luật mới, thằng nào phạm tội phải lau bảng trực nhật và bị phạt 10 nghìn. Làm thế để cho có hình phạt thật sự thì mới rút kinh nghiệm được. Vì thằng lớp trưởng có vẻ bận và không đáng tin tưởng lắm, cô giao cho mình chịu trách nhiệm. Chỉ sau một đêm mà từ chó lên thành voi, từ thằng chức quèn nhất lớp thành thằng nắm quyền sinh sát trong tay, đến lớp trưởng cũng không phải xoắn. Lúc đó chả sợ bố con thằng nào, léng phéng một phát là 10 nghìn với lau bảng trực nhật ngay tắp lự, lớp trưởng cung chỉ như thường dân thế thôi. Chỉ tiếc là uy tín sau đó sụt giảm nghiêm trọng, cô giao lại cho thằng thủ quỹ lo việc đó, lại quay lại làm thằng lớp phó lao động quèn. Tuy thời gian làm quan to có phần ngắn ngủi, mình đã cũng đã hiểu thế nào là cái cảm giác oai như cóc.\n' +
            '\n' +
            'Mà lớp cán bộ lớp chẳng sung sướng gì. Chẳng biết có được cái gì không ngoài cái danh, hữu danh vô thực. Nghĩ đúng kiểu làm quan ở Việt Nam, vô thực mà hữu danh, hữu luôn cả đống vấn đề lằng nhằng đi kèm nữa. Mình hồi đó làm nhiều khi thấy làm cũng khổ. Mà đấy mới là cái chức quèn lớp phó lao động, chứ làm mấy cái như kiểu lớp trưởng hay những cái đại khái thế thì còn khổ nữa. Nhiều lúc muốn làm đúng trách nhiệm cũng khó, mà không làm thì không xong. Hồi lớp 7, có lần có bọn đi trốn chơi điện tử giữa trưa, về lớp cô phát hiện ra, hỏi đội trưởng của lớp lúc đó là Quỳnh Anh là bọn nó đi đâu, mà Quỳnh Anh phải nói dối hộ là bọn nó đi làm bài tập tin. Giờ thi thoảng nhắc lại thì bọn nó vân cười với nhau mà nghĩ may mà hồi đó cô không phát hiện ra, chứ nếu không tự nhiên Quỳnh Anh phải hứng hết. Nhớ lớp 9, lớp trưởng của lớp mình là Tống Mỹ Linh, cãi nhau về một chuyện gì đó thuộc trách nhiệm của nó với một đứa bạn khá thân của nó trong lớp, mà đến nỗi giờ sinh hoạt, nó đứng giữa lớp, vừa giải thích với giáo viên vừa khóc. Nhìn nó lúc đó vừa tội vừa thương. Chẳng làm gì mà cũng phải giải thích.\n' +
            '\n' +
            'Làm lớp trưởng, hiền thì chẳng ai nghe, mà nghiêm thì ai cũng ghét. Nghiêm quá thì đứa nào cũng sợ và ghét vì mình bị phạt, chẳng có ai chơi cùng, cả lớp ghẻ lạnh. Chuyện này lớp mình học chưa bao giờ xảy ra, hoặc giả có xảy ra mình cũng không biết, nhưng mình cũng biết chuyện lớp khác. Mà hiền quá thì như Kiên, nói chẳng phải chứ nhiều khi có lẽ hiền đến vô dụng. Chẳng quản được lớp, nói chẳng ai nghe, chỉ như thằng gõ mõ của làng, nói thì cứ nói còn ai nghe hay không thì kệ. Mà thực ra cũng một phần vì lớp cấp 3 của mình hồi đó toàn thành phần bất hảo. Có thằng Trí thiết đầu công với anh Phương Bốc Lửa đến cô Hoa cũng chịu thì thằng Kiên đúng là cũng chẳng ăn gì được.',
    }
];
